version: "3.8"
services:
  server:
    build: 
      context: .
      args:
        URL: ${URL}
        AUTH_TOKEN: ${AUTH_TOKEN}
        PORT: ${PORT}
    env_file:
      - .env
    environment:
      URL: ${URL}
      AUTH_TOKEN: ${AUTH_TOKEN}
      PORT: ${PORT}
    runtime: nvidia
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]
