services:
  server:
    build: 
      context: .
      args:
        - URL=${URL}
        - AUTH_TOKEN=${AUTH_TOKEN}
        - PORT=${PORT}
    env_file:
      - .env
    environment:
      - URL=${URL}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - PORT=${PORT}
